# Generated by Django 5.0.4 on 2024-04-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_alter_client_created_by_delete_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_by',
        ),
    ]
